Module 7: Continuous Integration
CharlieCumber1/DevOps-Course-Starter-Module-3 pull request #5
Opened 2020-12-28 16:23 UTC by CharlieCumber1

2021-01-13 09:26 UTC, Jonesey13 commented
Designated Reviewer: Alex

2021-01-13 11:01 UTC, Jonesey13 requested changes
.

2021-01-28 10:12 UTC, JackMead approved these changes
Nice, some really clear changes here and I can see that travis built & ran your tests successfully against this pull request

2021-01-28 10:12 UTC, JackMead commented on README.md
> +### Option 2: Docker
Nice clear instructions

2021-03-02 11:32 UTC, merged